name: Build Simple APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      run: flutter pub get
        
    - name: Build debug APK
      run: flutter build apk --debug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ultmatestudentkit-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
